CREATE TABLE IF NOT EXISTS orders (
    ServiceId INTEGER PRIMARY KEY AUTO_INCREMENT,
    UserId INTEGER,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    StartDay DATE,
    EndDay DATE,
    IsActive BOOLEAN NOT NULL,
    CreatedBy VARCHAR(100) NOT NULL,
    Note TEXT,
    FOREIGN KEY (UserId) REFERENCES users(UserId) ON DELETE CASCADE
);