CREATE TABLE IF NOT EXISTS orders (
    ServiceId INTEGER PRIMARY KEY AUTOINCREMENT,
    UserId INTEGER,
    CreationDate TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP, 
    StartDay DATE,
    EndDay DATE,
    IsActive BOOLEAN NOT NULL PRIMARY KEY,
    CreatedBy VARCHAR(100) NOT NULL,
    Note TEXT 
);