CREATE TABLE IF NOT EXISTS users (
    UserId INTEGER PRIMARY KEY AUTO_INCREMENT ,
    Name VARCHAR(10) NOT NULL,
    SecondName VARCHAR(10),
    Surname VARCHAR(10) NOT NULL,
    Email VARCHAR(50) UNIQUE NOT NULL,
    PhoneNumber VARCHAR(12) UNIQUE NOT NULL
    );
